### ISSUE TITLE
Tracking Milestones

### ISSUE THREAD

**Issue by manishapriya94** [Ally-Guide/amplify-back-end#9]
## Features needed for each milestone (project board linked)

**1. MVP: Pilot letter parties with SoapBox, AAAJ, and the Breathe Act** (starting mid April 2021)
- [x] Architecture SetUp
- [ ] Create custom landing for each org
- [ ] Send message to letter function
- [ ] Dashboard for organization
 
**2. MVP+ Campaign Sponsors launched, scale 10 organizations.** (August 2021)
- [ ] Cause focused design refresh 
- [ ] Campaign Sponsors 
- [ ] Refined Dashboard for SetUp

**3. Alpha: Public facing site launched, scale 25 organizations.** (November 2021)
- [ ] Make project open source
- [ ] Text based functionality
